// Generated by CoffeeScript 2.3.2
(function() {
  /**
  interval, containing start and and

  @class Interval
  @module interval-tree2
  */
  var Interval;

  Interval = class Interval {
    /**
    @constructor
    @param {Number} start start of the interval
    @param {Number} end end of the interval
    @param {Number|String} id id of the interval
    */
    constructor(start, end, id) {
      this.start = start;
      this.end = end;
      this.id = id;
    }

    /**
    get center of the interval

    @method center
    @return {Number} center
    */
    center() {
      return (this.start + this.end) / 2;
    }

  };

  module.exports = Interval;

}).call(this);
