// Generated by CoffeeScript 2.3.2
(function() {
  var IntervalTree, i, interval, intervals, itree, len;

  IntervalTree = require('./interval-tree');

  itree = new IntervalTree(300);

  itree.add(22, 56, 'foo');

  itree.add(44, 199, 'bar');

  itree.add(1, 38, 'bar2');

  console.log(itree);

  intervals = itree.pointSearch(2);

  for (i = 0, len = intervals.length; i < len; i++) {
    interval = intervals[i];
    console.log(interval.id);
  }

}).call(this);
