// Generated by CoffeeScript 2.3.2
(function() {
  /**
  number with id

  @class Point
  @module interval-tree2
  */
  var Point;

  Point = class Point {
    /**
    @constructor
    @param {Number} val number
    @param {Number|String} id id
    */
    constructor(val, id) {
      this.val = val;
      this.id = id;
    }

  };

  module.exports = Point;

}).call(this);
