// Generated by CoffeeScript 2.3.2
(function() {
  var range_tree;

  range_tree = require('./store_tree');

  //user_pass_dict = new createjson('input_10m.txt');
  //user_pass_dict.save_key()

  //user_pass_dict.store_json();
  range_tree = new range_tree("0");

  range_tree.store_json();

}).call(this);
